{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "af8ec520-1dc8-4d0b-939a-d3d127829fcd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (1.37.1)\n",
      "Requirement already satisfied: numpy in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (1.26.4)\n",
      "Requirement already satisfied: altair<6,>=4.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (5.0.1)\n",
      "Requirement already satisfied: blinker<2,>=1.0.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (1.6.2)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (5.3.3)\n",
      "Requirement already satisfied: click<9,>=7.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (8.1.7)\n",
      "Requirement already satisfied: packaging<25,>=20 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (24.1)\n",
      "Requirement already satisfied: pandas<3,>=1.3.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (2.2.2)\n",
      "Requirement already satisfied: pillow<11,>=7.1.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (10.4.0)\n",
      "Requirement already satisfied: protobuf<6,>=3.20 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (4.25.3)\n",
      "Requirement already satisfied: pyarrow>=7.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (16.1.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (2.32.3)\n",
      "Requirement already satisfied: rich<14,>=10.14.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (13.7.1)\n",
      "Requirement already satisfied: tenacity<9,>=8.1.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (8.2.3)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.3.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (4.11.0)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (3.1.43)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (0.8.0)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from streamlit) (6.4.1)\n",
      "Requirement already satisfied: jinja2 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (3.1.4)\n",
      "Requirement already satisfied: jsonschema>=3.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
      "Requirement already satisfied: toolz in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit) (0.12.0)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from requests<3,>=2.27->streamlit) (2025.4.26)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)\n",
      "Requirement already satisfied: mdurl~=0.1 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)\n",
      "Requirement already satisfied: six>=1.5 in /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.3.0->streamlit) (1.16.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install streamlit numpy\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "753707c3-861e-40fc-91a2-53276c1b9d02",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-25 16:03:08.274 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run /Users/deepthi/Desktop/RUSHIKA/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-05-25 16:03:08.277 Session state does not function when running a script without `streamlit run`\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import numpy as np\n",
    "\n",
    "st.set_page_config(page_title=\"Matrix Calculator\", layout=\"centered\")\n",
    "\n",
    "st.title(\"🧮 Matrix Calculator (Streamlit UI)\")\n",
    "\n",
    "rows = st.number_input(\"Enter number of rows:\", min_value=1, max_value=10, value=2)\n",
    "cols = st.number_input(\"Enter number of columns:\", min_value=1, max_value=10, value=2)\n",
    "\n",
    "st.markdown(\"### Matrix A\")\n",
    "matrix_a = []\n",
    "for i in range(rows):\n",
    "    row = []\n",
    "    cols_ = st.columns(cols)\n",
    "    for j in range(cols):\n",
    "        row.append(cols_[j].number_input(f\"A[{i+1},{j+1}]\", key=f\"a_{i}_{j}\"))\n",
    "    matrix_a.append(row)\n",
    "A = np.array(matrix_a)\n",
    "\n",
    "st.markdown(\"### Matrix B\")\n",
    "matrix_b = []\n",
    "for i in range(rows):\n",
    "    row = []\n",
    "    cols_ = st.columns(cols)\n",
    "    for j in range(cols):\n",
    "        row.append(cols_[j].number_input(f\"B[{i+1},{j+1}]\", key=f\"b_{i}_{j}\"))\n",
    "    matrix_b.append(row)\n",
    "B = np.array(matrix_b)\n",
    "\n",
    "# Operation Selector\n",
    "st.markdown(\"### Choose Operation\")\n",
    "operation = st.selectbox(\"Operation\", [\"Add\", \"Subtract\", \"Multiply\", \"Transpose A\", \"Transpose B\", \"Inverse A\", \"Inverse B\"])\n",
    "\n",
    "# Perform Operation\n",
    "def perform_operation():\n",
    "    try:\n",
    "        if operation == \"Add\":\n",
    "            return A + B\n",
    "        elif operation == \"Subtract\":\n",
    "            return A - B\n",
    "        elif operation == \"Multiply\":\n",
    "            return A @ B\n",
    "        elif operation == \"Transpose A\":\n",
    "            return A.T\n",
    "        elif operation == \"Transpose B\":\n",
    "            return B.T\n",
    "        elif operation == \"Inverse A\":\n",
    "            if A.shape[0] != A.shape[1]:\n",
    "                st.error(\"Matrix A must be square.\")\n",
    "                return None\n",
    "            return np.linalg.inv(A)\n",
    "        elif operation == \"Inverse B\":\n",
    "            if B.shape[0] != B.shape[1]:\n",
    "                st.error(\"Matrix B must be square.\")\n",
    "                return None\n",
    "            return np.linalg.inv(B)\n",
    "    except np.linalg.LinAlgError:\n",
    "        st.error(\"Matrix is singular or non-invertible.\")\n",
    "        return None\n",
    "    except ValueError:\n",
    "        st.error(\"Dimension mismatch for the selected operation.\")\n",
    "        return None\n",
    "\n",
    "# Show result\n",
    "if st.button(\"Calculate\"):\n",
    "    result = perform_operation()\n",
    "    if result is not None:\n",
    "        st.markdown(\"### 🧾 Result\")\n",
    "        st.write(result)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8b482d5e-8344-4c09-9d28-c52dddd809bf",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
